#!/usr/bin/env python3
"""Create a complete text-only gist distribution without running proof code."""
from pathlib import Path
import hashlib
import shutil

ROOT = Path(__file__).resolve().parent
DEST = ROOT / "out" / "gist"
DEST.mkdir(parents=True, exist_ok=True)

# The certificate is regenerated by verify.sh from the distributed C++.
# Proof sources, pinned dependencies, logs, and reproduction scripts are text.
files = sorted(
    p for p in ROOT.iterdir()
    if p.is_file() and not p.name.startswith(".")
    and p.name not in {"partitions.bin.gz", "SHA256SUMS", "prepare-gist.py"}
)
files += sorted((ROOT / "C20MatchingFinite").glob("Head*.lean"))
restores = []
hashes = []
for src in files:
    relative = src.relative_to(ROOT).as_posix()
    flat = relative.replace("/", "__")
    shutil.copyfile(src, DEST / flat)
    hashes.append(f"{hashlib.sha256(src.read_bytes()).hexdigest()}  {relative}\n")
    if relative != flat:
        restores.append(f'cp -- "{flat}" "{relative}"')

(DEST / "restore-layout.sh").write_text(
    '#!/usr/bin/env bash\nset -euo pipefail\ncd -- "$(dirname -- "$0")"\n'
    'mkdir -p C20MatchingFinite\n' + "\n".join(restores) + '\n'
    'chmod +x verify.sh prepare-finite-workspace.sh\n'
)
(DEST / "SHA256SUMS").write_text("".join(sorted(hashes, key=lambda line: line.split("  ", 1)[1])))
(DEST / "00_README.md").write_text('''# Self-contained Berge–Fulkerson C(20) proof package

This gist contains the written proof, Lean sources, pinned dependency
manifest, finite enumerator and independent certificate replayer. It
requires no private repository or original research workspace.

**The complete main theorem `C20.c20` has passed Lean.** See
FORMALIZATION.md for the verified source commit, remote verification
links, exact axiom audit, and native-evaluation trust boundary.

Download or clone the entire gist, then restore the Lean module directory:

```sh
bash restore-layout.sh
sha256sum -c SHA256SUMS
bash verify.sh
```

`verify.sh` generates the binary certificate and checks its published
SHA-256, then independently replays every case. The banked binary is not
needed. On macOS, use `shasum -a 256 -c SHA256SUMS` for the hash check.

With elan installed, check the graph deduction with `lake build`. The full
formal target is `lake build C20Theorem`, followed by
`lake env lean C20Theorem.lean` to print its axiom dependencies. The finite
proof uses native evaluation with the additional trust documented in
FORMALIZATION.md. The computation is substantial.

Start with PROOF.md for the mathematics and README.md for scope, exact
counts, provenance, and links to remote checks.
''')
print(f"Prepared {len(files)} source files and three distribution files in {DEST}")
